name: Build and Publish

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # - name: Replacing placeholders of application properties
    #   run: |
    #     sed -i 's|${DATABASE_USERNAME}|${{ secrets.DATABASE_USERNAME }}|g' src/main/resources/application.properties
    #     sed -i 's|${DATABASE_PASSWORD}|${{ secrets.DATABASE_PASSWORD }}|g' src/main/resources/application.properties
    - name: build services images using gradle and publish
      run: |
        chmod +x ./gradlew
        echo "start building"
        ./gradlew bootBuildImage
        echo "done building..."
      env:
        DOCKER_LOGIN_USERNAME: ${{ secrets.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PW: ${{ secrets.DOCKER_LOGIN_PW }}

    - name: Copy docker-compose.yml to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        passphrase: ${{ secrets.SERVER_SSH_PW }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "docker-compose.yml"
        target: "servers/life-metaverse/server"


    - name: pull image and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        passphrase: ${{ secrets.SERVER_SSH_PW }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd servers/life-metaverse/server
          docker compose pull
          docker compose up -d
